### ISSUE TITLE
first use feedback

### ISSUE THREAD

**Issue by ckharri** [vanyle/SublimeNim#1] opened 2021-11-09 13:35 UTC
hi dev, thanks for your hard work!
I was looking to ditch the bulky vscode for my small nim scripting needs and love sublimetext.
Apparently you cornered the market since Google returns either the old NimLime (apparently the community ditched ST support in favor of VScode) or your SublimeNim, so well done.
Some things that are not obvious to me after trying the package:
- when I installed the package I couldn't build / run, the commands to build and run were greyed out. Don't know if it's broken on my end or it was if it was your choice to let the user configure the build script. Anyway I ended up copying and adapting the config from nimlime:
```
{
"cmd": ["nim", "r", "--verbosity:0", "$file"],
"selector": "source.nim",
"file_regex": "^(.+.nim)\\((\\d+), (\\d+)\\) (.*)",
}
```
- Highlighting, definitions and hints (very nice) work fine, I'm missing the automatic ident after blocks like if, for etc,. In that vein it would be nice to have a list of features you plan to implement in the future.

Thanks and gl

**Comment by vanyle** [comment] 2021-11-16 01:40
Thanks for your feedback !
I'm going to investigate the issue with `build` and `run`
I think that editing the config would be the simplest option.

**Comment by vanyle** [comment] 2021-11-16 16:07
You issue should be fixed in the latest version !
You need to reinstall the plugin to checkout the changes.

This was probably caused by me using Python 3.8 features without specifing to Sublime that this version should be used.

**Closed as completed** 2021-11-16 16:08 UTC

**Comment by ckharri** [comment] 2021-11-17 11:22
hey thanks it worked, no more grey areas and I can set my user preferences now.
some more feedback:
a) when I hit ctrl+b to run_nim, it runs against the last saved version of the program, I think the standard way to do it would be to automatically save the document before compiling and running to avoid the user the need of doing ctrl+s before doing ctrl+b
b) after hitting ctrl+b I noticed the terminal area was too small to read the output so I resized it, after some modifications and another ctrl+b the terminal area resized to original tiny version so I had to drag it again to the desired area. Don't know if it depends on some other general ST settings tho

**Comment by vanyle** [comment] 2021-11-17 12:06
For b)

By default, the sublime output panel has several issues:
- Disappears easily
- Needs to be resized every time
- You cannot interact with the program by using stdin

That's why we provide some custom terminal options (using a cmd window, or the terminus package).
I'm currently using terminus and it's a very good experience.
![image](https://user-images.githubusercontent.com/9964043/142197559-71a67c9b-cbcc-4f6b-948d-b4560034ae9d.png)

Details here: https://github.com/vanyle/SublimeNim#build-shortcuts


For a), this is an issue, I'm adding it to the list
